"""Criando as tabelas

Revision ID: 02c6fb64df67
Revises: 
Create Date: 2025-08-20 14:20:05.991683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02c6fb64df67'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_mesorregiao',
    sa.Column('codmesorregiao', sa.Integer(), nullable=False),
    sa.Column('mesorregiao', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('codmesorregiao')
    )
    op.create_table('tb_microrregiao',
    sa.Column('codmicrorregiao', sa.Integer(), nullable=False),
    sa.Column('microrregiao', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('codmicrorregiao')
    )
    op.create_table('tb_municipio',
    sa.Column('codmunicipio', sa.Integer(), nullable=False),
    sa.Column('nomemunicipio', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('codmunicipio')
    )
    op.create_table('tb_uf',
    sa.Column('coduf', sa.Integer(), nullable=False),
    sa.Column('uf', sa.String(), nullable=False),
    sa.Column('nomeestado', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('coduf')
    )
    op.create_table('tb_instituicao',
    sa.Column('codentidade', sa.Integer(), nullable=False),
    sa.Column('regiao', sa.String(), nullable=False),
    sa.Column('codregiao', sa.Integer(), nullable=False),
    sa.Column('uf', sa.String(), nullable=False),
    sa.Column('nomeestado', sa.String(), nullable=False),
    sa.Column('coduf', sa.Integer(), nullable=False),
    sa.Column('municipio', sa.String(), nullable=False),
    sa.Column('codmunicipio', sa.Integer(), nullable=False),
    sa.Column('mesorregiao', sa.String(), nullable=False),
    sa.Column('codmesorregiao', sa.Integer(), nullable=False),
    sa.Column('microrregiao', sa.String(), nullable=False),
    sa.Column('codmicrorregiao', sa.Integer(), nullable=False),
    sa.Column('entidade', sa.String(), nullable=False),
    sa.Column('matriculas_base', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['codmesorregiao'], ['tb_mesorregiao.codmesorregiao'], ),
    sa.ForeignKeyConstraint(['codmicrorregiao'], ['tb_microrregiao.codmicrorregiao'], ),
    sa.ForeignKeyConstraint(['codmunicipio'], ['tb_municipio.codmunicipio'], ),
    sa.ForeignKeyConstraint(['coduf'], ['tb_uf.coduf'], ),
    sa.PrimaryKeyConstraint('codentidade')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_instituicao')
    op.drop_table('tb_uf')
    op.drop_table('tb_municipio')
    op.drop_table('tb_microrregiao')
    op.drop_table('tb_mesorregiao')
    # ### end Alembic commands ###
